# Generated by Django 5.2.15 on 2026-06-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(default='Indonesia', max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='niche',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='target_audience',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='tone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
